os: macOS

language: go

go:
  - "1.14"

env:
  - export GO111MODULE="on"

before_install:  
  - sudo apt-get update   
  - sudo snap install docker

script:
  - docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test 
