FROM golang:1.14 as build

RUN apt-get update && apt-get install -y ninja-build


RUN go get -u github.com/Encelad/laba2/build/cmd/bood
WORKDIR build/
RUN bood

WORKDIR /go/src/practice-3
COPY . .
RUN go get -u gopkg.in/check.v1

ENTRYPOINT ["bood"]
